### ISSUE TITLE
Key Error: 'Granule Name'

### ISSUE THREAD

**Issue by elsadg** [ericlindsey/sentinel_query_download#1]
Hi @ericlindsey , 

I am getting this error when I run the code in python 3.6 through the command line.

![image](https://user-images.githubusercontent.com/37367962/96911249-842c1c80-1498-11eb-8ef1-7ceb1da147e1.png)

The result saved in the csv file looks like this: 
![image](https://user-images.githubusercontent.com/37367962/96911359-a9b92600-1498-11eb-8a27-e8511c6406e2.png)

 Could you please help?

Thank you!

**Comment by ericlindsey** [comment]
@elsadg there is a typo in your config file: it should be 'intersectsWith' not 'intersectWith'. The Key Error thrown by python then occurs because the search result is empty.

**Comment by ericlindsey** [comment]
Check out the full keyword list at the ASF API page: https://asf.alaska.edu/api/ - hope you find the code useful!

**Comment by elsadg** [comment]
Thank you @ericlindsey for updating the link! It was indeed a typo. Works now.
