### ISSUE TITLE
cannnot download the zip data

### ISSUE THREAD

**Issue by ShamirC** [ericlindsey/sentinel_query_download#2]
the code sucssesfully run , but I cannot download the zip files 
using this command: python sentinel_query_download.py sentinel_query.config --verbose   I can download the csv file , but when i get to the next step using this command: python sentinel_query_download.py sentinel_query.config --verbose --download  , I cannot download the zip 
the output is following:
Running ASF API query:
https://api.daac.asf.alaska.edu/services/search/param?output=csv&platform=Sentinel-1A,Sentinel-1B&processingLevel=SLC&beamMode=IW&intersectsWith=POLYGON((-107.7975 35.9141,-106.3267 34.9141,-106.3267 35.3502,-106.7975 35.3502,-107.7975 35.9141))&start=2019-04-05T00:00:00UTC&end=2019-05-05T00:00:00UTC&relativeOrbit=56

Query result saved to asf_query_2021_04_15-11_34_31.csv
Found 6 scenes.
Scene S1A_IW_SLC__1SDV_20190504T131059_20190504T131126_027078_030D08_D71A, Path 56 / Frame 477
Scene S1A_IW_SLC__1SDV_20190504T131035_20190504T131102_027078_030D08_D9ED, Path 56 / Frame 472
Scene S1A_IW_SLC__1SDV_20190422T131059_20190422T131126_026903_0306A6_A4FD, Path 56 / Frame 477
Scene S1A_IW_SLC__1SDV_20190422T131034_20190422T131101_026903_0306A6_B8F4, Path 56 / Frame 472
Scene S1A_IW_SLC__1SDV_20190410T131058_20190410T131125_026728_03005A_EE7F, Path 56 / Frame 477
Scene S1A_IW_SLC__1SDV_20190410T131034_20190410T131100_026728_03005A_33F2, Path 56 / Frame 472

Running 2 downloads in parallel.
Downloading granule  S1A_IW_SLC__1SDV_20190504T131059_20190504T131126_027078_030D08_D71A to directory P056/F0477
Try AWS download first.
wget -c --no-check-certificate -q http://sentinel1-slc-seasia-pds.s3-website-ap-southeast-1.amazonaws.com/datasets/slc/v1.1/2019/05/04/S1A_IW_SLC__1SDV_20190504T131059_20190504T131126_027078_030D08_D71A/S1A_IW_SLC__1SDV_20190504T131059_20190504T131126_027078_030D08_D71A.zip
Downloading granule  S1A_IW_SLC__1SDV_20190504T131035_20190504T131102_027078_030D08_D9ED to directory P056/F0472
Try AWS download first.
wget -c --no-check-certificate -q http://sentinel1-slc-seasia-pds.s3-website-ap-southeast-1.amazonaws.com/datasets/slc/v1.1/2019/05/04/S1A_IW_SLC__1SDV_20190504T131035_20190504T131102_027078_030D08_D9ED/S1A_IW_SLC__1SDV_20190504T131035_20190504T131102_027078_030D08_D9ED.zip
AWS download failed. Trying ASF download instead.
wget -c --no-check-certificate -q --http-user=shamirc --http-password=Lovecxm2021 https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20190504T131059_20190504T131126_027078_030D08_D71A.zip
AWS download failed. Trying ASF download instead.
wget -c --no-check-certificate -q --http-user=shamirc --http-password=Lovecxm2021 https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20190504T131035_20190504T131102_027078_030D08_D9ED.zip
ASF download failed. Granule not downloaded.
Downloading granule  S1A_IW_SLC__1SDV_20190422T131059_20190422T131126_026903_0306A6_A4FD to directory P056/F0477
Try AWS download first.
wget -c --no-check-certificate -q http://sentinel1-slc-seasia-pds.s3-website-ap-southeast-1.amazonaws.com/datasets/slc/v1.1/2019/04/22/S1A_IW_SLC__1SDV_20190422T131059_20190422T131126_026903_0306A6_A4FD/S1A_IW_SLC__1SDV_20190422T131059_20190422T131126_026903_0306A6_A4FD.zip
ASF download failed. Granule not downloaded.
Downloading granule  S1A_IW_SLC__1SDV_20190422T131034_20190422T131101_026903_0306A6_B8F4 to directory P056/F0472
Try AWS download first.
wget -c --no-check-certificate -q http://sentinel1-slc-seasia-pds.s3-website-ap-southeast-1.amazonaws.com/datasets/slc/v1.1/2019/04/22/S1A_IW_SLC__1SDV_20190422T131034_20190422T131101_026903_0306A6_B8F4/S1A_IW_SLC__1SDV_20190422T131034_20190422T131101_026903_0306A6_B8F4.zip
AWS download failed. Trying ASF download instead.
wget -c --no-check-certificate -q --http-user=shamirc --http-password=Lovecxm2021 https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20190422T131059_20190422T131126_026903_0306A6_A4FD.zip
AWS download failed. Trying ASF download instead.
wget -c --no-check-certificate -q --http-user=shamirc --http-password=Lovecxm2021 https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20190422T131034_20190422T131101_026903_0306A6_B8F4.zip
ASF download failed. Granule not downloaded.
Downloading granule  S1A_IW_SLC__1SDV_20190410T131058_20190410T131125_026728_03005A_EE7F to directory P056/F0477
Try AWS download first.
wget -c --no-check-certificate -q http://sentinel1-slc-seasia-pds.s3-website-ap-southeast-1.amazonaws.com/datasets/slc/v1.1/2019/04/10/S1A_IW_SLC__1SDV_20190410T131058_20190410T131125_026728_03005A_EE7F/S1A_IW_SLC__1SDV_20190410T131058_20190410T131125_026728_03005A_EE7F.zip
ASF download failed. Granule not downloaded.
Downloading granule  S1A_IW_SLC__1SDV_20190410T131034_20190410T131100_026728_03005A_33F2 to directory P056/F0472
Try AWS download first.
wget -c --no-check-certificate -q http://sentinel1-slc-seasia-pds.s3-website-ap-southeast-1.amazonaws.com/datasets/slc/v1.1/2019/04/10/S1A_IW_SLC__1SDV_20190410T131034_20190410T131100_026728_03005A_33F2/S1A_IW_SLC__1SDV_20190410T131034_20190410T131100_026728_03005A_33F2.zip
AWS download failed. Trying ASF download instead.
wget -c --no-check-certificate -q --http-user=shamirc --http-password=Lovecxm2021 https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20190410T131058_20190410T131125_026728_03005A_EE7F.zip
AWS download failed. Trying ASF download instead.
wget -c --no-check-certificate -q --http-user=shamirc --http-password=Lovecxm2021 https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20190410T131034_20190410T131100_026728_03005A_33F2.zip
ASF download failed. Granule not downloaded.
ASF download failed. Granule not downloaded.

Looks forward your anwser, thank you vey much!

**Comment by ericlindsey** [comment]
Hi Shamir, it looks like it is working fine, I am not sure why the ASF downloads have failed in this case.  Perhaps you hit some server maintenance period at ASF? 

The script output you provided contains the wget commands that are being run, but these all seem to work fine when I run them here, so I suggest trying it again. Also, you can copy the commands and run them individually yourself, and remove the "-q" flag to see more output on what is happening. Best of luck and thanks for using this code!
